In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

C:\Users\dipes\AppData\Local\Temp\ipykernel_20904\950747112.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [3]:
df = pd.read_csv("C:/Users/dipes/Downloads/machine_downtime_data.csv")

In [4]:
df

Machine_ID  Temperature  Run_Time  Downtime_Flag
0             7         75.9     462.5              0
1            20         75.8     990.4              0
2            15         72.4       1.2              0
3            11         86.8     186.3              0
4             8         69.9     384.6              0
..          ...          ...       ...            ...
495           5         83.4     186.0              1
496           3         48.5     917.8              0
497          11         82.3     425.1              0
498          11         72.8      88.0              0
499          18         85.0     815.9              0

[500 rows x 4 columns]

In [5]:
df.info

<bound method DataFrame.info of      Machine_ID  Temperature  Run_Time  Downtime_Flag
0             7         75.9     462.5              0
1            20         75.8     990.4              0
2            15         72.4       1.2              0
3            11         86.8     186.3              0
4             8         69.9     384.6              0
..          ...          ...       ...            ...
495           5         83.4     186.0              1
496           3         48.5     917.8              0
497          11         82.3     425.1              0
498          11         72.8      88.0              0
499          18         85.0     815.9              0

[500 rows x 4 columns]>

In [7]:
df.isnull()

Machine_ID  Temperature  Run_Time  Downtime_Flag
0         False        False     False          False
1         False        False     False          False
2         False        False     False          False
3         False        False     False          False
4         False        False     False          False
..          ...          ...       ...            ...
495       False        False     False          False
496       False        False     False          False
497       False        False     False          False
498       False        False     False          False
499       False        False     False          False

[500 rows x 4 columns]

In [8]:
df.describe()

Machine_ID  Temperature    Run_Time  Downtime_Flag
count  500.000000   500.000000  500.000000     500.000000
mean    10.176000    75.484600  504.635200       0.172000
std      6.035717    10.901033  292.109645       0.377758
min      1.000000    39.300000    1.200000       0.000000
25%      5.000000    68.700000  246.600000       0.000000
50%     10.000000    75.950000  522.600000       0.000000
75%     16.000000    82.825000  757.000000       0.000000
max     20.000000   106.700000  996.300000       1.000000

In [14]:
print(df.dtypes)

Machine_ID         int64
Temperature      float64
Run_Time         float64
Downtime_Flag      int64
dtype: object


In [15]:
y = df[["Downtime_Flag"]]
y.head()

Downtime_Flag
0              0
1              0
2              0
3              0
4              0

In [16]:
x = df.drop(columns="Downtime_Flag")
x.head()

Machine_ID  Temperature  Run_Time
0           7         75.9     462.5
1          20         75.8     990.4
2          15         72.4       1.2
3          11         86.8     186.3
4           8         69.9     384.6

In [17]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=42)

In [18]:
from sklearn.preprocessing import StandardScaler

In [19]:
from sklearn.preprocessing import StandardScaler

In [20]:
scaler = StandardScaler()

In [21]:
x_train = scaler.fit_transform(x_train)
x_train

array([[-0.53522309, -1.27430557,  1.41278518],
       [ 0.79452371,  1.69719608,  1.33251629],
       [-1.20009649,  1.35188396,  1.07055089],
       ...,
       [-1.03387814, -0.54733269, -1.22735589],
       [ 1.12696041,  0.35229625,  0.4613134 ],
       [-0.36900474,  1.00657184, -1.17832134]])

In [22]:
x_test = scaler.fit_transform(x_test)
x_test

array([[ 1.14305027e+00, -6.43119924e-01,  1.36261133e+00],
       [ 8.13006881e-01, -6.85693182e-02, -1.59749223e+00],
       [ 9.78028575e-01,  1.57483379e-01,  3.53263357e-01],
       [-1.21015909e-02, -2.14750062e-02,  1.20829998e+00],
       [-1.49729684e+00,  1.57483379e-01, -8.95682788e-01],
       [-1.49729684e+00, -7.79881806e-02,  8.80885282e-01],
       [-1.16725345e+00,  3.83536076e-01, -2.51066122e-02],
       [-8.37210063e-01,  2.98766315e-01,  2.63639907e-01],
       [ 4.82963492e-01, -1.21767053e+00,  1.34779455e+00],
       [-1.77123285e-01, -1.04813101e+00,  4.89772882e-02],
       [-1.00223176e+00,  1.66902241e-01, -1.43776011e+00],
       [-6.72188368e-01, -2.56946566e-01, -1.20285994e+00],
       [-1.00223176e+00,  2.23415416e-01,  1.01712738e+00],
       [-3.42144980e-01,  1.44786753e+00,  1.65343220e-01],
       [-3.42144980e-01, -2.63728147e-03, -1.10781571e+00],
       [-8.37210063e-01, -6.52538786e-01, -1.27838938e+00],
       [-8.37210063e-01,  7.32033985e-01

In [23]:
from sklearn.linear_model import LogisticRegression
regression = LogisticRegression()
regression.fit(x_train,y_train)

C:\Users\dipes\AppData\Roaming\Python\Python311\site-packages\sklearn\utils\validation.py:1229: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [24]:
test1 = scaler.transform([[7,62.67,9045]])

C:\Users\dipes\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [50]:
regression.predict(test1)

array([1], dtype=int64)

In [49]:
test2 = scaler.transform([[4,42.34,3866]])
regression.predict(test2)

C:\Users\dipes\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [30]:
y_pred = regression.predict(x_test)

In [31]:
from sklearn.metrics import accuracy_score

In [34]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

Accuracy: 0.8333333333333334


In [36]:
from sklearn.metrics import f1_score
f1 = f1_score(y_test, y_pred)
print(f"Model F1 Score: {f1:.2f}")

Model F1 Score: 0.00


In [40]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[125   0]
 [ 25   0]]


In [46]:
import pickle
pickle.dump(regression,open('machine downtime.pickle','wb'))

In [51]:
pickle.dump(regression,open('machine downtime1.pkl','wb'))

In [52]:
model = pickle.load(open('machine downtime.pickle','rb'))

In [53]:
model.predict(test1)

array([1], dtype=int64)

In [54]:
model.predict(test2)

array([0], dtype=int64)